### ISSUE TITLE
Add exclusion annotation in Prometheus Rules for the hosted use case

### ISSUE THREAD

**Issue by ryan-cradick** [openshift/cluster-autoscaler-operator#135]
The Prometheus Rules for this operator are being applied in the hosted use case. The exclude annotation needs to be added. This leads to an invalid alert.

https://github.com/openshift/cluster-autoscaler-operator/blob/master/install/09_alertrules.yaml

```
  annotations:
    exclude.release.openshift.io/internal-openshift-hosted: "true"
```

**Comment by enxebre** [comment]
https://github.com/openshift/cluster-autoscaler-operator/pull/134/files

**Comment by ryan-cradick** [comment]
Duplicate issue. Closing.
