### ISSUE TITLE
Update type for spec.resourceLimits

### ISSUE THREAD

**Issue by derekwaynecarr** [openshift/cluster-autoscaler-operator#17]
The types.go for resource limits should match vanilla kubernetes type definition for resource limits.

```
// ResourceList is a set of (resource name, quantity) pairs.
type ResourceList map[ResourceName]resource.Quantity
```

We can express a range for particular resources by just having a min/max similar to `LimitRange`

```
	Max ResourceList `json:"max,omitempty" protobuf:"bytes,2,rep,name=max,casttype=ResourceList,castkey=ResourceName"`
	// Min usage constraints on this kind by resource name.
	// +optional
	Min ResourceList `json:"min,omitempty" protobuf:"bytes,3,rep,name=min,casttype=ResourceList,castkey=ResourceName"`
```

/cc @bison @frobware @ingvagabund

**Comment by ingvagabund** [comment]
@derekwaynecarr what's the context here? Are you referring to a specific file, package in this repo or the cluster autoscaler?

**Comment by derekwaynecarr** [comment]
@ingvagabund 
https://github.com/openshift/cluster-autoscaler-operator/blob/master/pkg/apis/autoscaling/v1alpha1/clusterautoscaler_types.go#L45

**Comment by ingvagabund** [comment]
I see, just found https://github.com/openshift/cluster-autoscaler-operator/blob/master/examples/clusterautoscaler.yaml#L8 as well

**Comment by bison** [comment]
The types originally looked like this, but were changed to avoid having to normalize the values since the autoscaler expects plain integers. It's doable though. So, the limits would look like this then:

```yaml
limits:
  min:
    cpu: 8
    memory: 128Gb
    nvidia.com/gpu: 0
  max:
    cpu: 8
    memory: 64
    nvidia.com/gpu: 16
```

Does that look right?

**Comment by bison** [comment]
To be clear, the issue with using `resource.Quantity` is mostly that you can specify fractional values and/or values with units that don't make sense for a given resource. We can add validation for this though.

I guess it's a trade-off between looking like other Kubernetes resources and giving the user more room for error. I don't have a strong opinion either way really.

**Comment by bison** [comment]
@derekwaynecarr ping. Any thoughts on this? Happy to make the change, just want to be sure we're on the same page.

**Comment by enxebre** [comment]
Closing as this is not relevant anymore.
